name: project_1
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets\images\man.png
    - assets\images\imgplaceholder.jpg
    - assets\images\avoteklogo.png
    - assets\images\splashjpg.jpg


  fonts:
    - family: Poppins
      fonts:
        - asset: assets\fonts\Poppins-Black.ttf
          weight: 900
        - asset: assets\fonts\Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets\fonts\Poppins-Bold.ttf
          weight: 800
        - asset: assets\fonts\Poppins-BoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets\fonts\Poppins-Medium.ttf
          weight: 400
        - asset: assets\fonts\Poppins-Medium.ttf
          weight: 400
          style: italic
        - asset: assets\fonts\Poppins-Regular.ttf
          weight: 300
        - asset: assets\fonts\Poppins-Light.ttf
          weight: 200
        - asset: assets\fonts\Poppins-Light.ttf
          weight: 200
          style: italic
        - asset: assets\fonts\Poppins-Thin.ttf
          weight: 100
        - asset: assets\fonts\Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        
  
